### ISSUE TITLE
Allow support of multiple endpoints

### ISSUE THREAD

**Issue by j0nimost** [elliott-maguire/ergal#9]
As it stands right now, a user can only add a single endpoint to a single base url. My proposal suggests the addition of a table that is `endpoints` table. This `endpoints` table will hold the following information;
- API endpoints
- Request types for  each endpoint
- Targets
- ProfileID (Foreign Key)
- EndpointId (Primary Key)

**Comment by elliott-maguire** [comment]
This is not correct. The user can add as many endpoints as they please on a base URL, as long as the endpoints have different names.
